name: Publish Open Textbook

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths-ignore:
      - 'original/**'
      - 'README.md'

jobs:
  publish_textbook:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Download Source Files
        uses: actions/checkout@v3

      - name: Setup Pandoc
        run: brew install pandoc pandoc-crossref

      - name: Setup PagedJS-CLI
        run: npm install -g pagedjs-cli pagedjs 

      - name: Build Website
        run: |
          bash lantern.sh
          touch ./public/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
